2018-07-02 17:28:05,898 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-04 18:18:50,781 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-04 18:19:05,276 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-04 19:55:12,899 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-04 20:01:26,168 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-05 17:13:47,156 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-08 15:32:36,824 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-08 15:33:59,683 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-08 15:34:22,299 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-08 15:34:39,923 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-08 17:29:20,184 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-08 17:51:33,601 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-10 20:35:18,899 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-10 20:56:09,060 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-10 21:24:30,196 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:52]
2018-07-10 22:51:15,215 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:55]
2018-07-11 16:27:45,492 INFO: Microblog startup [in C:\Users\manoj\microblog\app\__init__.py:55]
2018-07-11 16:31:57,043 ERROR: Exception on /login [GET] [in c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\manoj\microblog\app\routes.py", line 57, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\manoj\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\manoj\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\manoj\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\manoj\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\manoj\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\manoj\microblog\app\templates\login.html", line 27, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\manoj\microblog\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2018-07-11 16:32:05,553 ERROR: Exception on /login [GET] [in c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\manoj\microblog\app\routes.py", line 57, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\manoj\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\manoj\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\manoj\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\manoj\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\manoj\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\manoj\microblog\app\templates\login.html", line 27, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\manoj\microblog\venv\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\manoj\microblog\venv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
